/**
 * @agent-page/server - public exports (APP v0.4-Ultimate)
 */

export * from './media-types.js';
export * from './types.js';
export {
  ERROR_REGISTRY,
  WARN_CODES,
  buildErrorEnvelope,
  resolveHttpStatus,
  errorContentType,
  detailString,
  getErrorMeta,
  AppError,
  type BuildErrorOptions,
  type ErrorCodeMeta,
} from './errors.js';
export {
  validateStateNode,
  validateStateRoot,
  assertValidStateNode,
  isValidCalendarDate,
  isRfc3339,
  NODE_MEMBERS,
  PAGINATION_MEMBERS,
  type ValidateStateOptions,
} from './validate-state.js';
export {
  validateManifestActions,
  validatePageBlock,
  validateNavigation,
  validatePresent,
  validateMeta,
  MAX_ACTIONS_PER_PAGE,
  PAGE_MEMBERS,
  NAV_MEMBERS,
  NAV_ITEM_MEMBERS,
  NAV_ITEM_RELS,
  ACTION_DEF_MEMBERS,
  PARAM_MEMBERS,
  OPTIONS_SOURCE_MEMBERS,
  PRESENT_MEMBERS,
  PRESENT_LAYOUTS,
  SECTION_MEMBERS,
  COLUMN_MEMBERS,
  COLUMN_FORMATS,
  COLUMN_ALIGNS,
  COMPONENT_TYPES,
  COMPONENT_MEMBERS,
  COMPONENT_VARIANTS,
  CHART_KINDS,
  TAB_MEMBERS,
  THEME_MEMBERS,
  A11Y_MEMBERS,
  LIVE_REGIONS,
  RESPONSIVE_MEMBERS,
  BREAKPOINT_MEMBERS,
} from './validate-manifest.js';
export {
  validateParams,
  canonicalizeParams,
  type ValidateParamsOptions,
} from './validate-params.js';
// ParamMode is exported from types.ts (ActionDef.param_mode)
export {
  validateActionRequest,
  parseActionRequestBody,
  checkIdempotencyKeyHeader,
  requiresIdempotencyKey,
  requiresConfirmation,
  type ValidateActionRequestOptions,
  type ActionRequestValidationResult,
  type ActionRequestValidationError,
} from './validate-action-request.js';
export {
  parseAcceptHeader,
  parseAcceptVersions,
  negotiate,
  selectProtocolVersion,
  contentTypeMatches,
  acceptsApp,
  type MediaRange,
  type NegotiationResult,
  type VersionSelection,
} from './negotiate.js';
export {
  checkCsrf,
  extractOriginFromUrl,
  normalizeOrigin,
  readCsrfHeaders,
  hasAuthCredentials,
  hasNonCookieAuth,
  type CsrfCheckInput,
  type CsrfCheckResult,
} from './csrf.js';
export {
  IDEMPOTENCY_TTL_MS,
  MemoryIdempotencyStore,
  hashRequestBody,
  computeIdempotencyFingerprint,
  lookupIdempotency,
  beginIdempotentRequest,
  storeIdempotentResponse,
  evaluateChallengeContinuation,
  isChallengeContinuationBody,
  bindChallengeBaseBody,
  challengeIdFromErrorDetails,
  idempotencyScope,
  type IdempotencyStore,
  type IdempotencyRecord,
  type IdempotencyLookupResult,
  type StoredResponse,
} from './idempotency.js';
export {
  CONFIRMATION_TTL_MS,
  CONFIRMATION_CLOCK_SKEW_MS,
  UUID_MODE_PREFIX,
  MemoryConfirmationStore,
  generateChallengeToken,
  issueConfirmationChallenge,
  bindUuidModeConfirmation,
  verifyConfirmation,
  consumeConfirmation,
  confirmationFingerprint,
  sha256Hex,
  isAgentClient,
  type ConfirmationStore,
  type ConfirmationBinding,
  type ConfirmationVerifyResult,
} from './confirmation.js';
export {
  generateDiff,
  buildDiffDocument,
  applyDiffDocument,
  validateDiffOps,
  isAllowedDiffPath,
  shouldPreferFullManifest,
  type DiffGenerateOptions,
} from './diff.js';
export {
  strongEtag,
  weakEtag,
  etagFromContent,
  parseIfNoneMatch,
  normalizeEtag,
  etagMatches,
  resolveManifestEtag,
} from './etag.js';
export {
  checkIfMatchVersion,
  bumpVersion,
  getPageVersion,
  type VersionCheckResult,
  type VersionCheckFailureReason,
} from './version.js';
export {
  DEFAULT_POLL_INTERVAL_MS,
  ASYNC_STATUS_OPTIONS,
  MemoryAsyncJobStore,
  buildAsyncPendingEnvelope,
  buildAsyncPendingManifest,
  buildOperationStatusNode,
  buildAsyncFailedSoftError,
  createAsyncJob,
  updateAsyncJobStatus,
  createCancelOperationHandler,
  type AsyncJob,
  type AsyncJobStatus,
  type AsyncJobStore,
} from './async-actions.js';
export {
  createPagination,
  attachPagination,
  paginateTable,
  paginateArray,
  encodeOffsetCursor,
  decodeOffsetCursor,
  getPagination,
  isTableNode,
  isArrayNode,
} from './pagination.js';
export { isLoopbackHost, isLoopbackUrl, isAllowedAppUrlScheme } from './loopback.js';
export {
  buildRateLimitHeaders,
  setRateLimitHeaders,
  MemoryRateBucket,
  createHoldRateLimiter,
  createOtpRateLimiter,
  type RateLimitInfo,
  type RateLimitHeaders,
  type BucketConsumeResult,
} from './rate-limit.js';
export { validateWellKnownManifest, buildCapabilitiesNode } from './well-known.js';
export {
  createPageHandler,
  appMiddleware,
  sendAppError,
  createFastifyPlugin,
  type AppServerOptions,
  type PageHandlerOptions,
  type RequestWithRawBody,
} from './middleware.js';
export { createAppServer, createApp, type CreateAppServerOptions } from './create-app.js';
export {
  installAppBodyParsing,
  appBodyErrorCheck,
  appBodyErrorHandler,
  APP_JSON_MEDIA_TYPES,
  APP_JSON_LIMIT,
} from './body-parse.js';
export {
  parseFeatureFlags,
  validateFeatureImplications,
  featureEnabled,
  type FeatureImplicationResult,
} from './features.js';
export {
  IDENTITY_CACHE_CONTROL,
  LOGIN_MAX_FAILURES,
  LOGIN_LOCKOUT_MS,
  identityCacheHeaders,
  newSessionId,
  rotateSessionId,
  MemoryIdentityLockoutStore,
  isIdentityLocked,
  evaluateLoginAttempt,
  evaluateSignup,
  recoveryStartResult,
  evaluateLogout,
  authRequiredDetails,
  type IdentityLockoutStore,
  type LockoutRecord,
  type LoginAttemptResult,
  type LogoutResult,
} from './identity.js';
export {
  RESUME_TOKEN_RE,
  DEFAULT_RESUME_TTL_SECONDS,
  MAX_RESUME_TTL_SECONDS,
  SESSION_CLOCK_SKEW_MS,
  hashSecret,
  mintResumeToken,
  mintRefreshToken,
  mintAccessToken,
  isResumeTokenFormat,
  clampResumeTtl,
  formatSetAppResume,
  MemorySessionStore,
  isSessionExpired,
  createAuthenticatedSession,
  authenticateWithResume,
  mintResume,
  rotateResume,
  spendRefreshToken,
  bumpSessionEpoch,
  findFamilyByRefreshToken,
  type SessionRecord,
  type RefreshFamily,
  type ResumeRecord,
  type SessionStore,
  type ResumeAuthResult,
  type RefreshResult,
} from './session.js';
export {
  CHALLENGE_ID_RE,
  OTP_MAX_LENGTH,
  CHALLENGE_TTL_MIN_MS,
  CHALLENGE_TTL_DEFAULT_MS,
  CHALLENGE_TTL_MAX_MS,
  DEFAULT_MAX_ATTEMPTS,
  MemoryChallengeStore,
  mintChallengeId,
  clampChallengeTtl,
  challengeToObject,
  issueOtpChallenge,
  issueWebauthnChallenge,
  verifyOtp,
  spendChallenge,
  verifyWebauthn,
  resendOtpChallenge,
  type ChallengeSlotStatus,
  type ChallengeRecord,
  type ChallengeStore,
  type ChallengeVerifyResult,
} from './challenge.js';
export {
  HOLD_WINDOW_MS,
  HOLD_MAX_PER_WINDOW,
  HOLD_TOKEN_TTL_AFTER_CLEAR_MS,
  HOLD_TTL_DEFAULT_MS,
  HOLD_TTL_MIN_MS,
  HOLD_TTL_MAX_MS,
  MemoryHoldStore,
  mintHoldId,
  mintHoldToken,
  clampHoldTtl,
  holdToObject,
  issueHold,
  completeHold,
  spendHoldToken,
  expireHold,
  clearHold,
  type HoldStatus,
  type HoldRecord,
  type HoldStore,
  type HoldIssueResult,
  type HoldCompleteResult,
  type HoldTokenResult,
} from './hold.js';
export {
  CLOSED_PURPOSES,
  isConsentPurposeId,
  emptyConsent,
  isGranted,
  grantMap,
  checkConsentGate,
  applyGrants,
  revokeConsent,
  bumpConsentVersion,
  assertConsentVersion,
  type ConsentGrantState,
  type ConsentState,
  type ConsentGateResult,
} from './consent.js';
export {
  OAUTH_SLOT_TTL_MS,
  generatePkcePair,
  MemoryOAuthStore,
  mintOAuthSlotId,
  mintOAuthState,
  bindOAuthCallback,
  completeOAuth,
  assertNoOAuthSecretsInBody,
  type PkcePair,
  type OAuthSlot,
  type OAuthTokenSet,
  type OAuthStore,
  type CompleteOAuthResult,
} from './oauth.js';
export {
  HEARTBEAT_MIN_MS,
  HEARTBEAT_MAX_MS,
  HEARTBEAT_DEFAULT_MS,
  LONGPOLL_TIMEOUT_MIN_MS,
  LONGPOLL_TIMEOUT_MAX_MS,
  LONGPOLL_TIMEOUT_DEFAULT_MS,
  EVENT_REPLAY_MAX,
  EVENT_REPLAY_WINDOW_MS,
  EVENT_MEDIA_TYPE,
  SSE_MEDIA_TYPE,
  clampHeartbeatInterval,
  clampLongpollTimeout,
  parseLongpollTimeout,
  MemoryEventStore,
  sameOrigin,
  formatSseMessage,
  formatSseRetry,
  validateEventRecord,
  heartbeatEvent,
  replayAfter,
  decideEventSubscription,
  collectReplay,
  longpollResult,
  type StoredEvent,
  type EventStore,
  type EventMode,
  type EventSubscribeInput,
  type EventSubscribeDecision,
  type LongpollResult,
} from './events.js';
export {
  PRESIGN_DEFAULT_TTL_MS,
  PRESIGN_CROSS_ORIGIN_SEND_COOKIES,
  MemoryPresignStore,
  mintFileId,
  sha256Hex as presignSha256Hex,
  allocateUploadSlot,
  verifyUploadReceipt,
  presignPutHeaders,
  type UploadSlot,
  type PresignStore,
  type PresignReceipt,
} from './presign.js';
export {
  validateOptionsSource,
  assertValidOptionsSource,
  validateActionOptionsSources,
  readOptionsSource,
  type OptionsSourceTarget,
} from './options-source.js';
export {
  isLegalTransition,
  isTerminalStatus,
  applyTransition,
  applyRefund,
  assertLegalTransition,
} from './order.js';
export {
  BULK_MAX_ITEMS,
  defaultBulkMode,
  resolveBulkMode,
  resolveBulkMaxItems,
  validateBulkItems,
  assertBulkAllowed,
  runBulk,
  type BulkMode,
  type ValidateBulkOptions,
  type BulkValidationResult,
  type BulkItemResult,
} from './bulk.js';
export {
  WARN_TIMEZONE_FALLBACK,
  WARN_LANGUAGE_FALLBACK,
  isBcp47,
  isIanaTimeZone,
  parseAcceptLanguage,
  resolveLocale,
  formatDatetimeForZone,
  type ResolveLocaleInput,
  type ResolveLocaleResult,
} from './locale.js';
export {
  projectStateNodeToV10,
  projectStateRootToV10,
  projectParamDefToV10,
  projectActionDefToV10,
  projectErrorEnvelopeToV10,
  projectManifestToV10,
} from './project-v10.js';
export * from './features.js';
export * from './identity.js';
export * from './session.js';
export * from './challenge.js';
export * from './hold.js';
export * from './consent.js';
export * from './oauth.js';
export * from './events.js';
export * from './presign.js';
export * from './options-source.js';
export * from './order.js';
export * from './bulk.js';
export * from './locale.js';
export * from './project-v10.js';
export {
  createAuthServer,
  signToken,
  verifyToken,
  parseScopes,
  scopeCovers,
  requiredScopeHint,
  MemoryCodeStore,
  MemoryRefreshStore,
} from './auth-server.js';
export type {
  TokenClaims,
  TokenRequest,
  TokenResponse,
  ClientRegistration,
  AuthorizeParams,
  AuthServerOptions,
  AuthCode,
  RefreshRecord,
  CodeStore,
  RefreshStore,
} from './auth-server.js';
